### ISSUE TITLE
v2.2.0 Startup crashes on 1.19.2

### ISSUE THREAD

**Issue by WimpieRatte** [JuneDeveloper/Minecraft-Vanilla-Notebook#59]
Startup crash.
Crash file: [https://mclo.gs/ygQnZ3G](url)

First part of the error file:

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-04-16 15:47:39
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'vanilla-notebook'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.IndexOutOfBoundsException: Index 8 out of bounds for length 7
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.june.notebook.Config.readCfg(Config.java:14)
	at com.june.notebook.Config.read(Config.java:36)
	at com.june.notebook.Notebook.re_init(Notebook.java:42)
	at com.june.notebook.Notebook.onInitialize(Notebook.java:130)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more

**Comment by JuneDeveloper** [comment]
Are you using the default config?
It's trying to access a page which doesn't exist - this could be because you deleted it and set the default as a page later on than that page, or did it manually.
Otherwise it is likely a bug.

**Comment by JuneDeveloper** [comment]
Any update to this issue?

**Comment by WimpieRatte** [comment]
Yes! This was the issue!
I deleted the contents of my config folder, then it worked, thanks! :D
